name: Lighthouse CI
on: [push]
jobs:
  lhci:
    name: Lighthouse CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: npm install & build
        run: |
          npm install
          npm run build
      - name: run Lighthouse CI
        uses: treosh/lighthouse-ci-action@v2
        with:
          configPath: './lighthouserc.json'
          uploadArtifacts: true
